# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Emscripten
      - name: Cache Emscripten SDK
        uses: actions/cache@v4
        with:
          path: emsdk
          key: emsdk-${{ runner.os }}-latest
      - name: Setup Emscripten
        run: |
          if [ ! -d "emsdk" ]; then
            git clone https://github.com/emscripten-core/emsdk.git
          fi
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
      - name: Activate Emscripten
        run: echo "$PWD/emsdk/upstream/emscripten" >> $GITHUB_PATH
      
      # Build game
      - name: Cache build folder
        uses: actions/cache@v4
        with:
          path: build_wasm
          key: build_wasm-${{ runner.os }}-${{ hashFiles('CMakeLists.txt','src/**') }}
      - name: Build game
        run: |
          source emsdk/emsdk_env.sh
          mkdir -p build_wasm
          cd build_wasm
          emcmake cmake ../ -B . -DCMAKE_BUILD_TYPE=Release -DCLAYBORNE_VENDORED=ON
          cmake --build . --target clayborne
          mkdir -p ../website/game
          cp clayborne.html ../website/game/index.html
          cp *.js ../website/game/ || echo "no JS generated"
          cp *.wasm ../website/game/ || echo "no WASM generated"
          cd ..

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./website/
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
